kind: Deployment
apiVersion: apps/v1
metadata:
  name: simple-inf
  labels:
    app: simple-inf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-inf
  template:
    metadata:
      labels:
        app: simple-inf
    spec:
      #nodeSelector:
      #  beta.kubernetes.io/instance-type: "c5.2xlarge"
      containers:
      - name: main
        image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
        imagePullPolicy: Always
        command: ["bash", "-c"]
        args: ["apt update", "apt install -y curl vim jq", "pip install transformers configparser fastapi uvicorn", "curl -L -o config.properties https://.....", ". /config.properties", "mkdir -p $model_save_path", "export HF_HOME=$model_save_path", "curl -L -o fastapi-server.py http://....", "uvicorn fastapi-server:app --host 0.0.0.0 --port 8080"]
        ports:
        - name: pod-port
          containerPort: 8080
        #resources:
        #  limits:
        #    cpu: 4
        #    memory: 4Gi
        #    nvidia.com/gpu: 1
        #    k8s.amazonaws.com/vgpu: 5
        #  requests:
        #    cpu: "1"
        #    memory: 1Gi
        #volumeMounts:
        #- name: nvidia-mps
        #  mountPath: /tmp/nvidia-mps
      #volumes:
      #- name: nvidia-mps
      #  hostPath:
      #    path: /tmp/nvidia-mps
---
kind: Service
apiVersion: v1
metadata:
  name: simple-inf
  namespace: simple-inf
  labels:
    app: simple-inf
spec:
  ports:
  - name: svc-port
    port: 8080
    targetPort: pod-port
  type: ClusterIP
  selector:
    app: simple-inf
