apiVersion: v1
kind: Service
metadata:
  name: etcd-cpu
spec:
  ports:
    - name: etcd-client-port
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd-cpu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etcd-cpu
  name: etcd-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-cpu
  template:
    metadata:
      labels:
        app: etcd-cpu
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: ml.m5.2xlarge
      containers:
        - name: etcd
          command: ["/usr/local/bin/etcd"]
          args:
            - "--data-dir"
            - "/var/lib/etcd"
            - "--enable-v2"
            - "--listen-client-urls"
            - "http://0.0.0.0:2379"
            - "--advertise-client-urls"
            - "http://0.0.0.0:2379"
            - "--initial-cluster-state"
            - "new"
          image: quay.io/coreos/etcd:v3.5.19
          ports:
            - containerPort: 2379
              name: client
              protocol: TCP
            - containerPort: 2380
              name: server
              protocol: TCP
      restartPolicy: Always
---
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: imagenet-cpu
  annotations: {
    sagemaker.amazonaws.com/enable-job-auto-resume: "true",
    sagemaker.amazonaws.com/job-max-retry-count: "2"
  }
spec:
  elasticPolicy:
    rdzvBackend: etcd
    rdzvHost: etcd-cpu
    rdzvPort: 2379
    minReplicas: 2
    maxReplicas: 24
    maxRestarts: 200
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
  pytorchReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          nodeSelector:
            node.kubernetes.io/instance-type: ml.m5.2xlarge
          containers:
            - name: pytorch
              image: kubeflow/pytorch-elastic-example-imagenet:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 1
              env:
              - name: LOGLEVEL
                value: DEBUG
              command:
                - python
                - -m
                - torch.distributed.run
                - /workspace/examples/imagenet.py
                - "--arch=resnet18"
                - "--epochs=20"
                - "--batch-size=32"
                - "--workers=0"
                - "/workspace/data/tiny-imagenet-200"
