apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
spec:
  #nodeSelector:
  #  node.kubernetes.io/instance-type: "ml.g6e.8xlarge"
  containers:
  - name: efs-pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo  \"hello from EFS\" - $(date -u) >> /efs-shared/test.txt; sleep 120; done"]
    volumeMounts:
    - name: efs-pvc
      mountPath: /efs-shared
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-pvc
