apiVersion: v1
kind: Pod
metadata:
  name: fsx-pod
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"FSx volume is accessible on\" $(date) >> /fsx/health.log; sleep 5; done"]
    volumeMounts:
    - name: fsx
      mountPath: /fsx
  volumes:
  - name: fsx
    persistentVolumeClaim:
      claimName: fsx-pvc
