apiVersion: karpenter.sagemaker.amazonaws.com/v1
kind: HyperpodNodeClass
metadata:
  name: sample-nc
spec:
  instanceGroups:
    # name of InstanceGroup in HyperPod cluster. InstanceGroup needs to pre-created
    # MaxItems: 10
    # Only using AZs where ml.g5.8xlarge is available (us-west-2a, us-west-2b, us-west-2c)
    - autoscaling-group